services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ./data:/app/backend/data
    environment:
      - WEBUI_AUTH=false
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
